name: Clean Enroll Workflows
on: push

steps:
  - name: Delete workflow runs
    uses: MajorScruffy/delete-old-workflow-runs@v0.1.0
    with:
      repository: ideacrew/enroll
      created-before: 2021-01-01T16:34:00Z
    env:
      GITHUB_TOKEN: ${{ secrets.GH_PAT }}
